# Generated by Django 6.0.2 on 2026-03-17 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_configcontafaturamento_relatorio_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('codigo', models.SlugField(max_length=80)),
                ('tipo', models.CharField(choices=[('MULT', 'Multiplicação'), ('PERCENTUAL', 'Percentual')], default='MULT', max_length=20)),
                ('unidade', models.CharField(blank=True, max_length=20)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioTaxaConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.contafaturamento')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorios.relatorioservico')),
            ],
        ),
    ]
