# Generated by Django 6.0.2 on 2026-03-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_configcontafaturamento_relatorio_config_and_more'),
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatorioservico',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Serviço de Relatório', 'verbose_name_plural': 'Serviços de Relatório'},
        ),
        migrations.AlterModelOptions(
            name='relatoriotaxaconta',
            options={'verbose_name': 'Taxa por Conta', 'verbose_name_plural': 'Taxas por Conta'},
        ),
        migrations.AddField(
            model_name='relatorioservico',
            name='metodo_calculo',
            field=models.CharField(choices=[('MANUAL', 'Valor Manual / Fixo'), ('PICO_VALOR_WMS', 'Pico de Valor em Estoque (Ad-Valorem)'), ('PICO_POSICAO_WMS', 'Pico de Posições Ocupadas (Armazenagem)')], default='MANUAL', help_text='Define qual regra de extração do WMS será usada para este serviço.', max_length=30),
        ),
        migrations.AlterField(
            model_name='relatorioservico',
            name='ordem',
            field=models.IntegerField(default=0, help_text='Ordem de exibição no relatório'),
        ),
        migrations.AlterField(
            model_name='relatorioservico',
            name='tipo',
            field=models.CharField(choices=[('MULT', 'Multiplicação (Qtd x Taxa)'), ('PERCENTUAL', 'Percentual (Valor x % Taxa)')], default='MULT', max_length=20),
        ),
        migrations.AlterField(
            model_name='relatorioservico',
            name='unidade',
            field=models.CharField(blank=True, help_text='Ex: UN, POS, R$', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='relatoriotaxaconta',
            unique_together={('conta', 'servico')},
        ),
    ]
