# Generated by Django 6.0.2 on 2026-03-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0002_alter_relatorioservico_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorioservico',
            name='metodo_calculo',
            field=models.CharField(choices=[('MANUAL', 'Valor Manual / Fixo'), ('PICO_POSICAO_SNAPSHOT', 'Pico de Posições (Maior contagem de locais no dia)'), ('PICO_VALOR_SNAPSHOT', 'Pico de Valor em Estoque (Maior soma de valor no dia)'), ('SOMA_VALOR_PERIODO', 'Soma de Valor no Período (Ad-valorem acumulado)'), ('SOMA_ESTOQUE_PERIODO', 'Soma de Peso/Qtd no Período (Armazenagem por Ton/Un)')], default='MANUAL', help_text='Define qual regra de extração da tabela de Snapshot será usada.', max_length=30),
        ),
        migrations.AlterField(
            model_name='relatorioservico',
            name='unidade',
            field=models.CharField(blank=True, help_text='Ex: UN, POS, R$, TON', max_length=20),
        ),
    ]
