# Generated by Django 6.0.2 on 2026-03-03 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_remove_contafaturamento_wms_local_prefix_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='clientes.cliente')),
            ],
            options={
                'ordering': ['cliente_id', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diarios', to='clientes.contafaturamento')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarios_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', 'conta_id'],
            },
        ),
        migrations.CreateModel(
            name='HoraExtraLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ATE_21', 'Após as 18h até 21h'), ('APOS_21_OU_FDS', 'Sáb/Dom/Feriados e após 21h')], max_length=20)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hora_extra_lancamentos', to='apontamentos.diario')),
            ],
            options={
                'ordering': ['diario_id', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='HoraExtraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_colaboradores', models.PositiveIntegerField(default=0)),
                ('qtd_horas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('valor_hh', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hora_extra_itens', to='apontamentos.cargo')),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='apontamentos.horaextralancamento')),
            ],
            options={
                'ordering': ['cargo__ordem', 'cargo__nome'],
            },
        ),
        migrations.CreateModel(
            name='MetricaTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80)),
                ('unidade', models.CharField(blank=True, max_length=20)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas_tipos', to='clientes.cliente')),
            ],
            options={
                'ordering': ['cliente_id', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='DiarioMetricaValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='apontamentos.diario')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valores', to='apontamentos.metricatipo')),
            ],
            options={
                'ordering': ['tipo__ordem', 'tipo__nome'],
            },
        ),
        migrations.CreateModel(
            name='TabelaHoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ATE_21', 'Após as 18h até 21h'), ('APOS_21_OU_FDS', 'Sáb/Dom/Feriados e após 21h')], max_length=20)),
                ('valor_hh', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tabelas_hh', to='apontamentos.cargo')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabela_hora_extra', to='clientes.contafaturamento')),
            ],
            options={
                'ordering': ['conta_id', 'cargo__ordem', 'cargo__nome', 'tipo'],
            },
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(fields=('cliente', 'nome'), name='uniq_cargo_cliente_nome'),
        ),
        migrations.AddConstraint(
            model_name='diario',
            constraint=models.UniqueConstraint(fields=('conta', 'data'), name='uniq_diario_conta_data'),
        ),
        migrations.AddConstraint(
            model_name='horaextralancamento',
            constraint=models.UniqueConstraint(fields=('diario', 'tipo'), name='uniq_diario_tipo_he'),
        ),
        migrations.AddConstraint(
            model_name='horaextraitem',
            constraint=models.UniqueConstraint(fields=('lancamento', 'cargo'), name='uniq_he_lancamento_cargo'),
        ),
        migrations.AddConstraint(
            model_name='metricatipo',
            constraint=models.UniqueConstraint(fields=('cliente', 'slug'), name='uniq_metrica_cliente_slug'),
        ),
        migrations.AddConstraint(
            model_name='diariometricavalor',
            constraint=models.UniqueConstraint(fields=('diario', 'tipo'), name='uniq_diario_tipo_metrica'),
        ),
        migrations.AddConstraint(
            model_name='tabelahoraextra',
            constraint=models.UniqueConstraint(fields=('conta', 'cargo', 'tipo'), name='uniq_hh_conta_cargo_tipo'),
        ),
    ]
