# Generated by Django 6.0.2 on 2026-03-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apontamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diariometricavalor',
            options={'ordering': ['tipo__categoria', 'tipo__ordem', 'tipo__nome']},
        ),
        migrations.AlterModelOptions(
            name='metricatipo',
            options={'ordering': ['cliente_id', 'categoria', 'ordem', 'nome']},
        ),
        migrations.AddField(
            model_name='metricatipo',
            name='categoria',
            field=models.CharField(db_index=True, default='Geral', help_text='Grupo/aba para organizar (ex: Pallets, Stage, Cancelados, Cross Docking).', max_length=40),
        ),
    ]
