# Generated by Django 5.2.8 on 2026-02-11 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContaFaturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('cnpj', models.CharField(db_index=True, max_length=14)),
                ('cnpj_wms', models.CharField(db_index=True, max_length=14)),
                ('wms_local_prefix', models.CharField(default='PP-', max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='UserConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('OPERADOR', 'Operador'), ('LEITURA', 'Leitura')], default='OPERADOR', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='clientes.contafaturamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='contafaturamento',
            index=models.Index(fields=['cliente', 'ativa'], name='clientes_co_cliente_492ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='contafaturamento',
            index=models.Index(fields=['cnpj'], name='clientes_co_cnpj_1d1f18_idx'),
        ),
        migrations.AddIndex(
            model_name='contafaturamento',
            index=models.Index(fields=['cnpj_wms'], name='clientes_co_cnpj_wm_0eeb06_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contafaturamento',
            unique_together={('cliente', 'slug')},
        ),
        migrations.AddIndex(
            model_name='userconta',
            index=models.Index(fields=['user', 'ativo'], name='clientes_us_user_id_92afee_idx'),
        ),
        migrations.AddIndex(
            model_name='userconta',
            index=models.Index(fields=['conta', 'ativo'], name='clientes_us_conta_i_d1b8be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userconta',
            unique_together={('user', 'conta')},
        ),
    ]
