# Generated by Django 5.2.8 on 2026-02-12 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contafaturamento',
            name='wms_local_prefix',
        ),
        migrations.CreateModel(
            name='ConfigContaFaturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_armazenagem', models.CharField(choices=[('PALLET_UNICO', 'Armazenagem por pallet único (distinct local)')], default='PALLET_UNICO', max_length=30)),
                ('wms_local_prefixes', models.JSONField(blank=True, default=list)),
                ('somente_com_estoque', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='clientes.contafaturamento')),
            ],
        ),
    ]
