# Generated by Django 6.0.2 on 2026-03-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_contafaturamento_wms_local_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configcontafaturamento',
            name='relatorio_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='configcontafaturamento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
